module.exports = {
  projects: [
    '<rootDir>/apps/time-tracker',
    '<rootDir>/apps/backend',
    '<rootDir>/libs/shared',
    '<rootDir>/libs/ui/layout',
    '<rootDir>/libs/common/home',
    '<rootDir>/libs/auth/core',
    '<rootDir>/libs/ui/status',
    '<rootDir>/libs/core/util',
    '<rootDir>/libs/core/store',
    '<rootDir>/libs/sessions/core',
    '<rootDir>/libs/tags/core',
    '<rootDir>/libs/tags/ui',
    '<rootDir>/libs/sessions/ui',
    '<rootDir>/libs/core/api',
    '<rootDir>/libs/core/services',
    '<rootDir>/libs/ui/menu',
    '<rootDir>/libs/ui/date-time',
    '<rootDir>/libs/ui/dialogs',
    '<rootDir>/libs/ui/notifications',
    '<rootDir>/libs/ui/animations',
    '<rootDir>/libs/errors/page-not-found',
  ],
};
